<?php
/* Smarty version 3.1.36, created on 2022-04-04 07:27:25
  from 'mailMessage:message' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.36',
  'unifunc' => 'content_624a81bd7bb962_84053914',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '652e3de8ff57f412acf7c0a8dadc70dc1a7637b6' => 
    array (
      0 => 'mailMessage:message',
      1 => 1649050045,
      2 => 'mailMessage',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_624a81bd7bb962_84053914 (Smarty_Internal_Template $_smarty_tpl) {
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>Manual Upgrade Required</title>
        <style type="text/css">
            [EmailCSS]
        </style>
    </head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
        <center>
            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">
                <tr>
                    <td align="center" valign="top" id="bodyCell">
                        <table border="0" cellpadding="0" cellspacing="0" id="templateContainer">
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader">
                                        <tr>
                                            <td valign="top" class="headerContent">
                                                <div style="max-width:600px;padding:20px 20px 0 20px">Company Name</div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody">
                                        <tr>
                                            <td valign="top" class="bodyContent">
                                                <p>An upgrade order has received its payment, but does not support automatic upgrades and requires manually processing.</p>
<p>Client ID: <?php echo $_smarty_tpl->tpl_vars['client_id']->value;?>
<br />Service ID: <?php echo $_smarty_tpl->tpl_vars['service_id']->value;?>
<br />Order ID: <?php echo $_smarty_tpl->tpl_vars['order_id']->value;?>
</p>
<p><?php if ($_smarty_tpl->tpl_vars['upgrade_type']->value == 'package') {?>New Package ID: <?php echo $_smarty_tpl->tpl_vars['new_package_id']->value;?>
<br />Existing Billing Cycle: <?php echo $_smarty_tpl->tpl_vars['billing_cycle']->value;?>
<br />New Billing Cycle: <?php echo $_smarty_tpl->tpl_vars['new_billing_cycle']->value;
} else { ?>Configurable Option: <?php echo $_smarty_tpl->tpl_vars['config_id']->value;?>
<br />Option Type: <?php echo $_smarty_tpl->tpl_vars['option_type']->value;?>
<br />Current Value: <?php echo $_smarty_tpl->tpl_vars['current_value']->value;?>
<br />New Value: <?php echo $_smarty_tpl->tpl_vars['new_value']->value;
}?></p>
<p><a href="<?php echo $_smarty_tpl->tpl_vars['whmcs_admin_url']->value;?>
orders.php?action=view&id=<?php echo $_smarty_tpl->tpl_vars['order_id']->value;?>
">
<?php echo $_smarty_tpl->tpl_vars['whmcs_admin_url']->value;?>
orders.php?action=view&id=<?php echo $_smarty_tpl->tpl_vars['order_id']->value;?>
</a></p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateFooter">
                                        <tr>
                                            <td valign="top" class="footerContent">
                                                <a href="https://www.whmcs.com/"><img src="https://cdn.whmcs.com/images/whmcs_email_footer.png" id="footerImage" alt="WHMCS" /></a>
                                                This notification was automatically generated by WHMCS<br />
                                                &nbsp;<a href="http://www.yourdomain.com/">http://www.yourdomain.com/</a>
                                                <span class="hide-mobile"> | </span>
                                                <a href="http://localhost/whm/admin/">log in to the admin area</a>&nbsp;
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html><?php }
}
